version: "3.9"  # optional since v1.27.0
services:
  nginx:
    container_name: nginx
    image: nginx
    networks:
      - backend
      - backendVpn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - instBack
